[package]
name = "year_2020"
version = "0.1.0"
authors = ["Cody Lee <cody.lee@datadoghq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]
members = [
    "puzzles/p_1_1",
    "puzzles/p_2",
]